INSERT INTO `gameplastforms` (`id`, `name`) VALUES
(1, 'PC'),
(2, 'PS4'),
(3, 'PS5'),
(4, 'XBOX'),
(5, 'WIIU'),
(6, 'SWITCH');

INSERT INTO `gamecategories` (`id`, `name`) VALUES
(1, 'Action'),
(2, 'Adventure'),
(3, 'RPG'),
(4, 'Strategy'),
(5, 'Shooter'),
(6, 'Simulation'),
(7, 'Arcade'),
(8, 'Platformer'),
(9, 'Racing'),
(10, 'MMO'),
(11, 'Sports'),
(12, 'Fighting');

INSERT INTO `games` (`id`, `name`, `description`, `coverImage`, `rating`, `price`, `createdAt`, `updatedAt`, `gamecategoryId`, `gameplatformId`) VALUES

('29a4e086-6ca6-4351-aec1-6f38285f4c6c','Red Dead Redemption 2','America, 1899. The end of the wild west era has begun as lawmen hunt down the last remaining outlaw gangs. Those who will not surrender or succumb are killed.  After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him.  From the creators of Grand Theft Auto V and Red Dead Redemption, Red Dead Redemption 2 is an epic tale of life in America at the dawn of the modern age.',
'coverImage-1637463179218-2786361045747-Rdr2_cover.jpg',5.0,39.99,3,1,'2021-11-21 05:52:59','2021-11-21 05:52:59'),
('4b980b8a-9608-4a36-83a5-4d8a7bae9bcb','Monster Hunter: World','Monster Hunter: World is the fifth game in the Japanese franchise Monster Hunter, which is about hunting giant beasts. It is set in a medieval fantasy setting, on a continent known as the New World that is being colonized by the humans from the Old World. The plot revolves around a dragon migration called Elder Crossing. Your protagonist is a hunter, whose name and appearance can be customized. You traveled from the Old World to study and hunt the dragons and other local monsters. The hunter, accompanied by an assistant, starts at the city of Astera, from where they can freely wander the open world. There are six regions in the New World, each with its own base camp. The camps are where you have to thoroughly prepare before every expedition, gathering equipment and provision. Before you can fight monsters, they need to be tracked down using Scout flies and studied to discover their habits, strengths, and weaknesses. There are no character levels, so your hunter’s effectiveness relies on the hunting gear you have equipped. Advanced armor and weapons can be created using a detailed crating system. Many items that you found on missions, including body parts of monsters, can be used for crafting.',
'coverImage-1637462938744-8649513780150-MHW_cover.jpg',4.5,19.99,2,1,'2021-11-21 05:48:58','2021-11-21 05:48:58'),
('544cbbf6-25b3-42dd-85e3-7f4c29b638a1','FIFA 22','HyperMotion integrates advanced full-team mocap data and machine learning to heighten gameplay in every match in FIFA 22, harnessing the power of next generation consoles to deliver the most realistic, responsive and fluid gameplay experience we’ve ever built. FIFA 22 brings a new season of innovation across every mode in the game; enjoy more consistency between the posts with a goalkeeper rewrite that brings more composure to the most important position on the pitch, live out your football dreams as you create and manage your custom club to glory in Career Mode, get rewarded for your flair with restyled gameplay in VOLTA FOOTBALL, welcome back football’s most memorable players as FIFA Ultimate Team™ Heroes, and feel the atmosphere of your next big game with the most immersive matchday experience ever seen in EA SPORTS FIFA.',
'coverImage-1637372022611-1842946859350-fifa22_cover.jpg',4.5,49.99,1,1,'2021-11-20 04:51:24','2021-11-21 22:20:36'),
('572cec2b-1797-4df7-bbb2-24ad52118ab4','DmC: Devil May Cry','DMC: Devil May Cry is a hack-and-slash adventure game, the fifth installment in Capcom’s Devil May Cry franchise and reboot of the series. This is the first game in the series not developed by Capcom, but rather by English studio Team Ninja. Concerning story, the game is connected to the previous game and changes the cast of characters and even Dante’s (the series main protagonist) iconic appearance (which was met with indignation from the series fans at the time). The game’s story is notable for its social commentary regarding mass-media and modern capitalism drawbacks. The gameplay overall is very similar to the other installments of the Devil May Cry series and is heavily focused on fast-paced fighting with hordes of demons with occasional puzzles and platforming sections. The main change in the game’s combat mechanics is the Angel and Devil modes. They alternate Dante’s and attacks and special abilities. The modes are activated by holding left or right trigger (on the controller) which makes switching between them instant and allows performing complex combos, combining each mode’s unique features.',
'coverImage-1638160165090-8035784335596-DMC_cover.jpg',4.8,19.99,1,1,'2021-11-29 04:29:25','2021-11-29 04:29:25'),
('80a9590e-f5c7-4e67-899b-9e6f6bf6e0ef','Grand Theft Auto V','Rockstar Games went bigger, since their previous installment of the series. You get the complicated and realistic world-building from Liberty City of GTA4 in the setting of lively and diverse Los Santos, from an old fan favorite GTA San Andreas. 561 different vehicles (including every transport you can operate) and the amount is rising with every update. Simultaneous storytelling from three unique perspectives: Follow Michael, ex-criminal living his life of leisure away from the past, Franklin, a kid that seeks the better future, and Trevor, the exact past Michael is trying to run away from. GTA Online will provide a lot of additional challenge even for the experienced players, coming fresh from the story mode. Now you will have other players around that can help you just as likely as ruin your mission. Every GTA mechanic up to date can be experienced by players through the unique customizable character, and community content paired with the leveling system tends to keep everyone busy and engaged.',
'coverImage-1638159458293-100597047125-GTAV_cover.jpg',5.0,10.99,1,1,'2021-11-29 04:17:38','2021-11-29 04:17:38'),
('8f7e9bf3-eee7-4638-9bf2-e71f970330a4','Escape from Tarkov','Escape from Tarkov is a hardcore and realistic online first-person action RPG/Simulator with MMO features and a story-driven walkthrough. With each passing day the situation in the Norvinsk region grows more and more complicated. Incessant warfare in Tarkov has sparked massive panic; the local population has fled the city, but those who stayed are looking to improve their fortunes at the expense of others. Having accepted the new reality, savage Tarkov locals - "Scavs" flocked into well-armed gangs and started the redivision of the city. Nowadays, Tarkov is separated by unseen borders, controlled by different groups. Gain-greedy gunmen would go to any length to have their way, including the murder of civilians and direct confrontation with the two private military companies. The players will have to experience living in the skin of one of the mercenaries who survived the initial stage of the Tarkov conflict. After choosing one of the sides – USEC or BEAR – the player’s character starts to make his way out of the city. Tarkov is sealed off by UN and Russian military, supply chains are cut, communication with operational command is lost, and in these conditions everyone has to make his own choices of what to do and how to get out of the chaos-ridden metropolis',
'coverImage-1637463549403-5872474667728-Tarkov_cover.jpg',4.5,44.99,2,1,'2021-11-21 05:59:09','2021-11-21 05:59:09'),
('921266b8-5d0b-4e07-afe2-6b77cd64a46e','Cyberpunk 2077','Cyberpunk 2077 is a science fiction game loosely based on the role-playing game Cyberpunk 2020. The game is set in the year 2077 in a fictional futuristic metropolis Night City in California. In the world of the game, there are developed cybernetic augmentations that enhance people''s strength, agility, and memory. The city is governed by corporations. Many jobs are taken over by the robots, leaving a lot of people poor and homeless. Night City has a roaring underworld, with black markets, underground surgeons, drug dealers, and street gangs abound.',
'coverImage-1638158600065-1622868793091-Cyberpunk_cover.jpeg',4.7,24.99,3,1,'2021-11-29 04:03:20','2021-11-29 04:03:20');